# Generated by Django 5.2.5 on 2025-11-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModeJamKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('warna', models.CharField(default='#3B82F6', help_text='Warna HEX untuk UI', max_length=7)),
                ('icon', models.CharField(default='fa-clock', help_text='Icon FontAwesome', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Semakin tinggi = lebih diutamakan jika overlap')),
                ('is_default', models.BooleanField(default=False, help_text='Mode default jika tidak ada periode aktif')),
                ('is_libur', models.BooleanField(default=False, help_text='Apakah mode ini adalah hari libur?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode Jam Kerja',
                'verbose_name_plural': 'Mode Jam Kerja',
                'db_table': 'master_mode_jam_kerja',
                'ordering': ['-priority', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ModeJamKerjaPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Ramadhan 1446H, Natal 2025', max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('tahun', models.IntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_list', to='absensi_app.mastermodejamkerja')),
            ],
            options={
                'verbose_name': 'Periode Mode Jam Kerja',
                'verbose_name_plural': 'Periode Mode Jam Kerja',
                'db_table': 'mode_jam_kerja_periode',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='ModeJamKerjaJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('is_hari_kerja', models.BooleanField(default=True)),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('jam_istirahat_keluar', models.TimeField(blank=True, null=True)),
                ('jam_istirahat_masuk', models.TimeField(blank=True, null=True)),
                ('toleransi_terlambat', models.IntegerField(default=15, help_text='Dalam menit')),
                ('toleransi_pulang_cepat', models.IntegerField(default=15, help_text='Dalam menit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='absensi_app.mastermodejamkerja')),
            ],
            options={
                'verbose_name': 'Jadwal Mode Jam Kerja',
                'verbose_name_plural': 'Jadwal Mode Jam Kerja',
                'db_table': 'mode_jam_kerja_jadwal',
                'ordering': ['mode', 'hari'],
                'unique_together': {('mode', 'hari')},
            },
        ),
        migrations.CreateModel(
            name='PegawaiExcludedMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jam_kerja_alternatif', models.ForeignKey(blank=True, help_text='Jam kerja yang digunakan saat mode ini aktif (kosong = pakai jam kerja normal)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi_app.masterjamkerja')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_pegawai', to='absensi_app.mastermodejamkerja')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_modes', to='absensi_app.pegawai')),
            ],
            options={
                'verbose_name': 'Pegawai Excluded Mode',
                'verbose_name_plural': 'Pegawai Excluded Mode',
                'db_table': 'pegawai_excluded_mode',
                'unique_together': {('pegawai', 'mode')},
            },
        ),
    ]
