# Generated by Django 5.2.5 on 2025-11-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0002_mastermodejamkerja_modejamkerjaperiode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaiexcludedmode',
            name='jam_kerja_alternatif',
        ),
        migrations.AddField(
            model_name='pegawaiexcludedmode',
            name='jadwal_alternatif',
            field=models.ForeignKey(blank=True, help_text='Jadwal alternatif untuk pegawai ini (jika tidak sama dengan mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi_app.modejamkerjajadwal'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Rendah'), (1, 'Normal'), (2, 'Tinggi'), (3, 'Sangat Tinggi')], default=1, help_text='Semakin tinggi = lebih diutamakan jika overlap periode'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjaperiode',
            index=models.Index(fields=['tanggal_mulai', 'tanggal_selesai'], name='mode_jam_ke_tanggal_0e4925_idx'),
        ),
    ]
