# Generated by Django 5.2.5 on 2025-11-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0003_remove_pegawaiexcludedmode_jam_kerja_alternatif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='jam_kerja',
        ),
        migrations.AlterModelOptions(
            name='mastermodejamkerja',
            options={'ordering': ['-is_default', '-priority', 'nama'], 'verbose_name': 'Mode Jam Kerja', 'verbose_name_plural': 'Mode Jam Kerja'},
        ),
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'hari']},
        ),
        migrations.AlterModelOptions(
            name='modejamkerjaperiode',
            options={'ordering': ['-tanggal_mulai']},
        ),
        migrations.AlterModelOptions(
            name='pegawaiexcludedmode',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='modejamkerjaperiode',
            name='mode_jam_ke_tanggal_0e4925_idx',
        ),
        migrations.RemoveField(
            model_name='modejamkerjajadwal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modejamkerjajadwal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modejamkerjaperiode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pegawaiexcludedmode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='is_shift',
            field=models.BooleanField(default=False, help_text='Mode untuk pegawai shift (24/7 operation)'),
        ),
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='untuk_departemen',
            field=models.ManyToManyField(blank=True, help_text='Kosongkan jika untuk semua departemen', related_name='mode_jam_kerja_list', to='absensi_app.masterdepartemen'),
        ),
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='untuk_jabatan',
            field=models.ManyToManyField(blank=True, help_text='Kosongkan jika untuk semua jabatan', related_name='mode_jam_kerja_list', to='absensi_app.masterjabatan'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='mode_jam_kerja',
            field=models.ForeignKey(blank=True, help_text='Mode jam kerja pegawai (akan auto-switch saat periode khusus)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.mastermodejamkerja'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='icon',
            field=models.CharField(default='fa-clock', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mode default untuk pegawai yang belum di-assign'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_libur',
            field=models.BooleanField(default=False, help_text='Mode untuk hari libur (tidak ada jam kerja)'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='kode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Default (Terendah)'), (1, 'Normal'), (2, 'Periode Khusus (Medium)'), (3, 'Urgent (Tinggi)')], default=1, help_text='Priority tinggi akan override mode lain saat periode aktif'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='warna',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_pulang_cepat',
            field=models.IntegerField(default=15, help_text='Toleransi pulang cepat (menit)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_terlambat',
            field=models.IntegerField(default=15, help_text='Toleransi keterlambatan (menit)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='catatan',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='nama',
            field=models.CharField(help_text='Nama periode (contoh: Ramadhan 2025)', max_length=100),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tahun',
            field=models.IntegerField(help_text='Tahun periode (untuk filtering)'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='catatan',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='jadwal_alternatif',
            field=models.ForeignKey(blank=True, help_text='Jadwal pengganti saat mode ini aktif', null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi_app.modejamkerjajadwal'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_from_modes', to='absensi_app.pegawai'),
        ),
        migrations.DeleteModel(
            name='MasterJamKerja',
        ),
    ]
