# Generated by Django 5.2.5 on 2025-11-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0004_remove_pegawai_jam_kerja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'departemen', 'hari']},
        ),
        migrations.AlterUniqueTogether(
            name='modejamkerjajadwal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modejamkerjajadwal',
            name='departemen',
            field=models.ForeignKey(default=1, help_text='Jadwal ini untuk departemen mana', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_mode_list', to='absensi_app.masterdepartemen'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='modejamkerjajadwal',
            unique_together={('mode', 'departemen', 'hari')},
        ),
    ]
