# Generated by Django 5.2.5 on 2025-11-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0005_alter_modejamkerjajadwal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'departemen', 'hari', 'nama_shift']},
        ),
        migrations.AlterUniqueTogether(
            name='modejamkerjajadwal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modejamkerjajadwal',
            name='nama_shift',
            field=models.CharField(default='Shift Utama', help_text='Nama shift: Shift 1, Shift 2, dst', max_length=50),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='shift_assignment',
            field=models.JSONField(blank=True, default=dict, help_text='Assignment shift per hari (JSON): {hari: nama_shift}'),
        ),
    ]
