# Generated by Django 5.2.5 on 2025-11-25 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0006_alter_modejamkerjajadwal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'departemen', 'hari', 'urutan', 'nama_shift']},
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='untuk_departemen',
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='untuk_jabatan',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='shift_assignment',
        ),
        migrations.RemoveField(
            model_name='pegawaiexcludedmode',
            name='jadwal_alternatif',
        ),
        migrations.AddField(
            model_name='modejamkerjajadwal',
            name='urutan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='shift_per_hari',
            field=models.JSONField(blank=True, default=dict, help_text='Assignment shift per hari dalam seminggu'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='icon',
            field=models.CharField(default='fa-clock', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_libur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Default (Terendah)'), (1, 'Normal'), (2, 'Periode Khusus (Medium)'), (3, 'Urgent (Tinggi)')], default=1),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='warna',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='departemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_mode_list', to='absensi_app.masterdepartemen'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='nama_shift',
            field=models.CharField(default='Shift Utama', help_text='Nama shift: Shift Pagi, Shift Siang, Shift Malam, dll', max_length=50),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_pulang_cepat',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_terlambat',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tahun',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='mode_jam_kerja',
            field=models.ForeignKey(blank=True, help_text='Mode jam kerja pegawai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.mastermodejamkerja'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjajadwal',
            index=models.Index(fields=['mode', 'departemen', 'hari'], name='mode_jam_ke_mode_id_d63071_idx'),
        ),
    ]
