# Generated by Django 5.2.5 on 2025-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0007_alter_modejamkerjajadwal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermodejamkerja',
            options={'ordering': ['-priority', 'nama'], 'verbose_name': 'Mode Jam Kerja', 'verbose_name_plural': 'Mode Jam Kerja'},
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='is_libur',
        ),
        migrations.RemoveField(
            model_name='mastermodejamkerja',
            name='is_shift',
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Periode Khusus'), (3, 'Urgent')], default=1),
        ),
    ]
