# Generated by Django 5.2.5 on 2025-11-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0008_alter_mastermodejamkerja_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'departemen', 'hari', 'urutan', 'nama_shift'], 'verbose_name': 'Jadwal Mode Jam Kerja', 'verbose_name_plural': 'Jadwal Mode Jam Kerja'},
        ),
        migrations.AlterModelOptions(
            name='modejamkerjaperiode',
            options={'ordering': ['-tanggal_mulai'], 'verbose_name': 'Periode Mode Jam Kerja', 'verbose_name_plural': 'Periode Mode Jam Kerja'},
        ),
        migrations.AlterModelOptions(
            name='pegawaiexcludedmode',
            options={'verbose_name': 'Pegawai Exception Mode', 'verbose_name_plural': 'Pegawai Exception Mode'},
        ),
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Hanya 1 mode yang bisa jadi default. Mode ini akan digunakan jika tidak ada mode lain yang aktif.', verbose_name='Mode Default'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Mode'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='nama',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Mode'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Periode Khusus'), (3, 'Urgent')], default=1, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='warna',
            field=models.CharField(default='#3B82F6', help_text='Warna untuk UI (HEX format)', max_length=7, verbose_name='Warna'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='departemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_mode_list', to='absensi_app.masterdepartemen', verbose_name='Departemen'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='hari',
            field=models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], verbose_name='Hari'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='is_hari_kerja',
            field=models.BooleanField(default=True, verbose_name='Hari Kerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_keluar',
            field=models.TimeField(blank=True, null=True, verbose_name='Istirahat Keluar'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_masuk',
            field=models.TimeField(blank=True, null=True, verbose_name='Istirahat Masuk'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_keluar',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Keluar'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Masuk'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='absensi_app.mastermodejamkerja', verbose_name='Mode Jam Kerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='nama_shift',
            field=models.CharField(default='Shift Utama', help_text='Nama shift: Shift Pagi, Shift Siang, Shift Malam, dll', max_length=50, verbose_name='Nama Shift'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_pulang_cepat',
            field=models.IntegerField(default=15, verbose_name='Toleransi Pulang Cepat (menit)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_terlambat',
            field=models.IntegerField(default=15, verbose_name='Toleransi Terlambat (menit)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='urutan',
            field=models.IntegerField(default=1, verbose_name='Urutan Shift'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='catatan',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_list', to='absensi_app.mastermodejamkerja', verbose_name='Mode Jam Kerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Periode'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tahun',
            field=models.IntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tanggal_selesai',
            field=models.DateField(verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='catatan',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_pegawai', to='absensi_app.mastermodejamkerja', verbose_name='Mode yang Dikecualikan'),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_from_modes', to='absensi_app.pegawai', verbose_name='Pegawai'),
        ),
        migrations.AddIndex(
            model_name='mastermodejamkerja',
            index=models.Index(fields=['is_default', 'is_active'], name='master_mode_is_defa_715548_idx'),
        ),
        migrations.AddIndex(
            model_name='mastermodejamkerja',
            index=models.Index(fields=['priority'], name='master_mode_priorit_43ea00_idx'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjajadwal',
            index=models.Index(fields=['mode', 'hari'], name='mode_jam_ke_mode_id_636a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjaperiode',
            index=models.Index(fields=['tanggal_mulai', 'tanggal_selesai'], name='mode_jam_ke_tanggal_0e4925_idx'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjaperiode',
            index=models.Index(fields=['is_active'], name='mode_jam_ke_is_acti_0d18d3_idx'),
        ),
        migrations.AddIndex(
            model_name='pegawaiexcludedmode',
            index=models.Index(fields=['pegawai', 'is_active'], name='pegawai_exc_pegawai_c56e0e_idx'),
        ),
    ]
