# Generated by Django 5.2.5 on 2025-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0009_alter_modejamkerjajadwal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='icon',
            field=models.CharField(default='fas fa-clock', help_text="Font Awesome icon class (e.g., 'fas fa-clock', 'fas fa-sun')", max_length=50, verbose_name='Icon'),
        ),
    ]
