# Generated by Django 5.2.5 on 2025-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0010_mastermodejamkerja_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='icon',
            field=models.CharField(default='fas fa-clock', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Mode Default'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='warna',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Warna'),
        ),
    ]
