# Generated by Django 5.2.5 on 2025-11-28 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0011_alter_mastermodejamkerja_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegawaiModeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal_per_hari', models.JSONField(default=dict, help_text='Format: {"0": jadwal_id, "1": jadwal_id, ...} (0=Senin, 6=Minggu)', verbose_name='Jadwal Per Hari')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_assignments', to='absensi_app.mastermodejamkerja', verbose_name='Mode')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_assignments', to='absensi_app.pegawai', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Assignment Mode Pegawai',
                'verbose_name_plural': 'Assignment Mode Pegawai',
                'db_table': 'pegawai_mode_assignment',
                'indexes': [models.Index(fields=['pegawai', 'mode'], name='pegawai_mod_pegawai_6a9d32_idx')],
                'unique_together': {('pegawai', 'mode')},
            },
        ),
    ]
