# Generated by Django 5.2.5 on 2025-11-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0013_alter_modejamkerjajadwal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modejamkerjajadwal',
            name='departemen',
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='group_name',
            field=models.CharField(help_text='Contoh: Shift Pagi, Shift Siang, Shift Malam', max_length=100, verbose_name='Nama Grup Jam Kerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_keluar',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Istirahat Keluar'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_masuk',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Istirahat Masuk'),
        ),
    ]
