# Generated by Django 5.2.5 on 2025-11-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0014_remove_modejamkerjajadwal_departemen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='DataRaw'),
        migrations.DeleteModel(name='DataTrans'),
        migrations.DeleteModel(name='HariLibur'),
        migrations.DeleteModel(name='AbsensiTracking'),
        migrations.DeleteModel(name='PenilaianKinerja'),
    ]