# Generated by Django 5.2.5 on 2025-12-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0015_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='Prioritas'),
        ),
    ]
