# Generated by Django 5.2.5 on 2025-12-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0016_alter_mastermodejamkerja_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercabang',
            name='ip_mesin_fingerprint',
            field=models.TextField(blank=True, help_text='Daftar IP mesin fingerprint, dipisahkan koma', null=True),
        ),
        migrations.AlterField(
            model_name='masterdepartemen',
            name='id_departemen',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='ID Departemen'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Nama Grup Jam Kerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jam_kerja_assignment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='shift_per_hari',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pegawaiexcludedmode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodeassignment',
            name='jadwal_per_hari',
            field=models.JSONField(default=dict, verbose_name='Jadwal Per Hari'),
        ),
    ]
