# Generated by Django 5.2.5 on 2025-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0017_alter_mastercabang_ip_mesin_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modejamkerjaperiode',
            name='is_periode_khusus',
            field=models.BooleanField(default=False, help_text='Centang jika ini periode khusus (libur nasional, ramadhan, dll)', verbose_name='Periode Khusus'),
        ),
        migrations.AddField(
            model_name='modejamkerjaperiode',
            name='warna_periode',
            field=models.CharField(blank=True, help_text='Warna periode dalam format hex (contoh: #10b981 untuk hijau)', max_length=7, null=True, verbose_name='Warna Periode'),
        ),
        migrations.AddIndex(
            model_name='modejamkerjaperiode',
            index=models.Index(fields=['is_periode_khusus'], name='mode_jam_ke_is_peri_add02b_idx'),
        ),
    ]
