# Generated by Django 5.2.5 on 2025-12-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0018_modejamkerjaperiode_is_periode_khusus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaiexcludedmode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='is_periode_khusus',
            field=models.BooleanField(default=False, help_text='Tandai periode khusus (opsional)', verbose_name='Periode Khusus'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='warna_periode',
            field=models.CharField(blank=True, help_text='Warna periode (opsional, untuk laporan)', max_length=7, null=True, verbose_name='Warna Periode'),
        ),
        migrations.CreateModel(
            name='AbsensiSesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(db_index=True, verbose_name='Tanggal Mulai Sesi')),
                ('tanggal_selesai', models.DateField(db_index=True, verbose_name='Tanggal Selesai Sesi')),
                ('tap_masuk_pertama', models.TimeField(verbose_name='Tap Masuk Pertama')),
                ('tap_masuk_terakhir', models.TimeField(blank=True, null=True, verbose_name='Tap Masuk Terakhir')),
                ('tap_pulang_pertama', models.TimeField(blank=True, null=True, verbose_name='Tap Pulang Pertama')),
                ('tap_pulang_terakhir', models.TimeField(blank=True, null=True, verbose_name='Tap Pulang Terakhir')),
                ('jumlah_tap_masuk', models.IntegerField(default=0, verbose_name='Jumlah Tap Masuk')),
                ('jumlah_tap_pulang', models.IntegerField(default=0, verbose_name='Jumlah Tap Pulang')),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=20, verbose_name='Status Sesi')),
                ('is_cross_day', models.BooleanField(default=False, verbose_name='Lintas Hari')),
                ('durasi_kerja_menit', models.IntegerField(blank=True, null=True, verbose_name='Durasi Kerja (menit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_kerja', to='absensi_app.pegawai', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Sesi Absensi',
                'verbose_name_plural': 'Sesi Absensi',
                'db_table': 'absensi_sesi',
                'ordering': ['tanggal_mulai', 'tap_masuk_pertama'],
            },
        ),
        migrations.CreateModel(
            name='TapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, verbose_name='Tanggal')),
                ('waktu_tap', models.TimeField(verbose_name='Waktu Tap')),
                ('punch_type', models.IntegerField(choices=[(0, 'Masuk'), (1, 'Keluar'), (2, 'Istirahat Keluar'), (3, 'Istirahat Masuk')], default=0, verbose_name='Jenis Tap')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Sudah Diproses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Record')),
                ('mesin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='absensi_app.mastermesin', verbose_name='Mesin')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_logs', to='absensi_app.pegawai', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Tap Log',
                'verbose_name_plural': 'Tap Logs',
                'db_table': 'tap_log',
                'ordering': ['tanggal', 'waktu_tap'],
            },
        ),
        migrations.CreateModel(
            name='TapSesiRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan_dalam_sesi', models.IntegerField(default=0, verbose_name='Urutan dalam Sesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absensi_sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_relation', to='absensi_app.absensisesi', verbose_name='Absensi Sesi')),
                ('tap_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_relation', to='absensi_app.taplog', verbose_name='Tap Log')),
            ],
            options={
                'verbose_name': 'Relasi Tap-Sesi',
                'verbose_name_plural': 'Relasi Tap-Sesi',
                'db_table': 'tap_sesi_relation',
                'ordering': ['absensi_sesi', 'urutan_dalam_sesi'],
            },
        ),
        migrations.AddIndex(
            model_name='absensisesi',
            index=models.Index(fields=['pegawai', 'tanggal_mulai'], name='absensi_ses_pegawai_b5d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='absensisesi',
            index=models.Index(fields=['tanggal_mulai', 'status'], name='absensi_ses_tanggal_7a6fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='taplog',
            index=models.Index(fields=['pegawai', 'tanggal'], name='tap_log_pegawai_d64353_idx'),
        ),
        migrations.AddIndex(
            model_name='taplog',
            index=models.Index(fields=['pegawai', 'tanggal', 'is_processed'], name='tap_log_pegawai_6f08b7_idx'),
        ),
        migrations.AddIndex(
            model_name='taplog',
            index=models.Index(fields=['tanggal', 'is_processed'], name='tap_log_tanggal_ea9074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tapsesirelation',
            unique_together={('tap_log', 'absensi_sesi')},
        ),
    ]
