# Generated by Django 5.2.5 on 2025-12-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0019_pegawaiexcludedmode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pegawaiexcludedmode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pegawaiexcludedmode',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='pegawaiexcludedmode',
            name='pegawai',
        ),
        migrations.AlterModelOptions(
            name='absensi',
            options={'ordering': ['-tanggal', '-tap_masuk']},
        ),
        migrations.AlterModelOptions(
            name='absensisesi',
            options={'ordering': ['tanggal_mulai', 'tap_masuk_pertama']},
        ),
        migrations.AlterModelOptions(
            name='fingerprinttemplate',
            options={'ordering': ['pegawai', 'fid']},
        ),
        migrations.AlterModelOptions(
            name='mastercabang',
            options={'ordering': ['nama'], 'verbose_name': 'Cabang', 'verbose_name_plural': 'Cabang'},
        ),
        migrations.AlterModelOptions(
            name='masterdepartemen',
            options={'ordering': ['id_departemen', 'nama'], 'verbose_name': 'Departemen', 'verbose_name_plural': 'Departemen'},
        ),
        migrations.AlterModelOptions(
            name='masterjabatan',
            options={'ordering': ['nama'], 'verbose_name': 'Jabatan', 'verbose_name_plural': 'Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='mastermesin',
            options={'ordering': ['cabang', 'nama'], 'verbose_name': 'Mesin Absensi', 'verbose_name_plural': 'Mesin Absensi'},
        ),
        migrations.AlterModelOptions(
            name='modejamkerjajadwal',
            options={'ordering': ['mode', 'group_name', 'hari', 'urutan'], 'verbose_name': 'Jadwal Mode', 'verbose_name_plural': 'Jadwal Mode'},
        ),
        migrations.AlterModelOptions(
            name='modejamkerjaperiode',
            options={'ordering': ['-tanggal_mulai'], 'verbose_name': 'Periode Mode', 'verbose_name_plural': 'Periode Mode'},
        ),
        migrations.AlterModelOptions(
            name='pegawaimodeassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taplog',
            options={'ordering': ['tanggal', 'waktu_tap']},
        ),
        migrations.AlterModelOptions(
            name='tapsesirelation',
            options={'ordering': ['absensi_sesi', 'urutan_dalam_sesi']},
        ),
        migrations.RemoveIndex(
            model_name='modejamkerjaperiode',
            name='mode_jam_ke_is_peri_add02b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='modejamkerjajadwal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tap_istirahat_keluar',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tap_istirahat_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tap_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tap_pulang',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='durasi_kerja_menit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='jumlah_tap_masuk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='jumlah_tap_pulang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_kerja', to='absensi_app.pegawai'),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='status',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tanggal_mulai',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tanggal_selesai',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tap_masuk_pertama',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tap_masuk_terakhir',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tap_pulang_pertama',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensisesi',
            name='tap_pulang_terakhir',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastercabang',
            name='ip_mesin_fingerprint',
            field=models.TextField(blank=True, default='', help_text='...'),
        ),
        migrations.AlterField(
            model_name='masterdepartemen',
            name='id_departemen',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='masterdepartemen',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='masterjabatan',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='cabang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesin', to='absensi_app.mastercabang'),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='lokasi',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='icon',
            field=models.CharField(default='fas fa-clock', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='kode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='warna',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Nama Grup'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='hari',
            field=models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')]),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_keluar',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_istirahat_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_keluar',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='absensi_app.mastermodejamkerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='catatan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='is_periode_khusus',
            field=models.BooleanField(default=False, help_text='Periode khusus'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_list', to='absensi_app.mastermodejamkerja'),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tahun',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tanggal_mulai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='tanggal_selesai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='modejamkerjaperiode',
            name='warna_periode',
            field=models.CharField(blank=True, default='', help_text='Warna untuk laporan (opsional)', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.mastercabang'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.masterdepartemen'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='is_shift_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.masterjabatan'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='mesin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='absensi_app.mastermesin'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nama_lengkap',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='tanggal_bergabung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='tanggal_nonaktif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodeassignment',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_assignments', to='absensi_app.mastermodejamkerja'),
        ),
        migrations.AlterField(
            model_name='pegawaimodeassignment',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_assignments', to='absensi_app.pegawai'),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='mesin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='absensi_app.mastermesin'),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_logs', to='absensi_app.pegawai'),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='punch_type',
            field=models.IntegerField(choices=[(0, 'Masuk'), (1, 'Keluar'), (2, 'Istirahat Keluar'), (3, 'Istirahat Masuk')], default=0),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='tanggal',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taplog',
            name='waktu_tap',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tapsesirelation',
            name='absensi_sesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_relation', to='absensi_app.absensisesi'),
        ),
        migrations.AlterField(
            model_name='tapsesirelation',
            name='tap_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_relation', to='absensi_app.taplog'),
        ),
        migrations.AlterField(
            model_name='tapsesirelation',
            name='urutan_dalam_sesi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='modejamkerjajadwal',
            unique_together={('mode', 'group_name', 'hari', 'urutan')},
        ),
        migrations.AddIndex(
            model_name='pegawaimodeassignment',
            index=models.Index(fields=['is_active'], name='pegawai_mod_is_acti_7cae26_idx'),
        ),
        migrations.DeleteModel(
            name='PegawaiExcludedMode',
        ),
    ]
