# Generated by Django 5.2.5 on 2025-12-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0020_alter_pegawaiexcludedmode_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodejamkerja',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Cabang yang menggunakan mode ini. Kosongkan untuk GLOBAL.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_jam_kerja_list', to='absensi_app.mastercabang'),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='kode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermodejamkerja',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='mastermodejamkerja',
            index=models.Index(fields=['cabang', 'is_active'], name='master_mode_cabang__a4d41f_idx'),
        ),
        migrations.AddConstraint(
            model_name='mastermodejamkerja',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nama', 'cabang'), name='unique_mode_per_cabang'),
        ),
    ]
