# Generated by Django 5.2.5 on 2025-12-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_app', '0021_mastermodejamkerja_cabang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercabang',
            name='ip_mesin_fingerprint',
            field=models.TextField(blank=True, default='', help_text='Daftar IP mesin fingerprint (pisahkan dengan koma)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_pulang_cepat',
            field=models.IntegerField(default=1, verbose_name='Toleransi Pulang Cepat (menit)'),
        ),
        migrations.AlterField(
            model_name='modejamkerjajadwal',
            name='toleransi_terlambat',
            field=models.IntegerField(default=5, verbose_name='Toleransi Terlambat (menit)'),
        ),
    ]
